export const images = {
  sevilla: "/assets/laligas/sev.png",
  realmadrid: "/assets/laligas/realM.png",
  barcelona: "/assets/laligas/barca.jpg",
  laliga: "/assets/laligas/laliga.jpg",
  bundesliga: "/assets/laligas/bundseliga.png",
  bpl: "/assets/laligas/bpl.png",
  copa: "/assets/laligas/copa.svg",
  rightFoot: "/assets/icons/feetpics/left_active.jpg ",
  leftFoot: "/assets/icons/feetpics/right_active.jpg ",
  ronaldo: "/assets/players/leagues/realmadrid/ronaldo.jpg",
  uefatrophy: "/assets/trophies/uefa.jpg",
  laligaTrophy: "/assets/trophies/laliga.png",
  copaTrophy: "/assets/trophies/copadel.png",
  cronaldo: "/assets/players/players/ron.png",
};
